"""Init2

Revision ID: 02cf105aa302
Revises: f95e2b97bad9
Create Date: 2023-08-19 01:23:15.290777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02cf105aa302'
down_revision: Union[str, None] = 'f95e2b97bad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('preferred_hours', sa.String(length=550), nullable=False),
    sa.Column('hold_back', sa.String(length=550), nullable=False),
    sa.Column('start_preference', sa.String(length=550), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
