"""Init5

Revision ID: 6401ba300dcc
Revises: c05f0110f5fc
Create Date: 2023-08-19 13:01:34.989274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6401ba300dcc'
down_revision: Union[str, None] = 'c05f0110f5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_goals', sa.Integer(), nullable=True))
    op.drop_column('users', 'active_targets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_targets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'active_goals')
    # ### end Alembic commands ###
