"""Init2

Revision ID: f45ef3238cc7
Revises: c14e441448e9
Create Date: 2023-08-20 12:40:29.939289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45ef3238cc7'
down_revision: Union[str, None] = 'c14e441448e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profile_user_id_fkey', 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_profile_user_id_fkey', 'user_profile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
